Fix core not appear, using jot for shuffling in BSD

diff --git a/benchy b/benchy
--- a/benchy
+++ b/benchy
@@ -3,7 +3,7 @@
 # Heavily influenced by masonr's Yet-Another-Bench-Script
 # https://github.com/masonr/yet-another-bench-script
 # shellcheck disable=SC2183,SC2030,SC2086,SC2181,SC2031
-currentVersion="v2.2"
+currentVersion="v2.2"; rev_date="26 Oct 2022"
 header_intro() {
   startTime=$(awk 'BEGIN {srand(); print srand()}')
   currentDate=$(date +"%d %b %Y %H:%M %Z")
@@ -42,9 +42,12 @@ Options:
 EOT
 }
 is_installed() { command -v $1 >/dev/null 2>&1; }
-is_openbsd() {
-    [ "$(uname)" = "OpenBSD" ] && return 0 || return 1
-}
+die() { printf "%s\n" "$@" >&2; return 1; }
+case $(uname | tr '[:upper:]' '[:lower:]') in
+  linux*) osv="linux";;
+  *bsd*) osv="bsd";;
+  *) die "OS Not supported"; exit 1;;
+esac
 # Prioritize curl over wget
 if is_installed curl; then
   # 0 Implies curl
@@ -53,7 +56,7 @@ elif is_installed wget; then
   # 1 Implies wget
   filegrab=1
 else
-  printf "%s\n" "Neither wget nor curl is exist" "Please install it first" >&2
+  die "Neither wget nor curl is exist" "Please install it first"
   exit 1
 fi
 # BEGIN OPTION PARSING (source https://stackoverflow.com/a/62616466/12289283)
@@ -71,7 +74,7 @@ if [ "$#" != 0 ]; then
       -j|--json) arg_json="true";;
       -m|--region) arg_use_region="true";;
       -e|--grab-env)
-      printf "%s" "Pulling env file to current directory"
+      printf "%s" "Pulling env file to home directory"
       if [ "$filegrab" -eq 0 ]; then
         curl -o "${HOME}/.benchy_opt" -kLs --connect-timeout 5 --retry 5 --retry-delay 0 "https://raw.githubusercontent.com/L1so/benchy/main/.benchy_opt"
       elif [ "$filegrab" -eq 1 ]; then
@@ -112,7 +115,7 @@ if [ "$#" != 0 ]; then
       esac
       ;;
       -h|--help) display_help; exit 0;;
-      -v|--version) printf "%s\n" "$currentVersion"; exit 0;;
+      -v|--version) printf "%-8s %-1s %s\n" "Version" ":" "$currentVersion" "Revision" ":" "$rev_date"; exit 0;;
       -|''|[!-]*) set -- "$@" "$opt";;
       --*=*)      set -- "${opt%%=*}" "${opt#*=}" "$@";;
       -[!-]?*)    set -- $(echo "${opt#-}" | sed 's/\(.\)/ -\1/g') "$@";;
@@ -132,7 +135,7 @@ fi
 [ -n "$arg_json" ] && logext="json" || logext="log"
 if [ -n "$arg_output_file" ]; then outputdir="${outputdir:-${PWD}}"; test -f "${outputdir}/benchy.${logext}" && rm -f "${outputdir}/benchy.${logext}"; fi
 outputdir="${outputdir:-/tmp}"
-{ [ ! -d $outputdir ] || [ ! -w $outputdir ] ; } && { >&2 printf "%s\n" "$outputdir does not exist or not writable" && exit 2; }
+{ [ ! -d $outputdir ] || [ ! -w $outputdir ] ; } && { die "$outputdir does not exist or not writable" && exit 2; }
 if [ -z "$arg_json" ] && { [ -n "$arg_output_file" ] || [ -n "$outputdir" ]; } || { [ -z "$arg_skip_disk" ] && [ -z "$arg_skip_network" ] && [ -z "$arg_skip_gb" ]; }; then parseit="true"; fi
 { [ -z "$arg_use_region" ] && [ -z "$continent" ]; } && continent="Mixed"
 
@@ -142,7 +145,7 @@ core_pkg() {
   is_installed locale && export LC_ALL=$(locale -a|grep -ix 'c.utf-\?8' || echo C)
   for pkg in tput tar; do
     if ! is_installed $pkg; then
-      printf "%s\n" "$pkg missing from your system"
+      die "$pkg missing from your system"
       exit 1
     fi
   done
@@ -357,12 +360,11 @@ binarycheck() {
     [ -n "$arg_use_region" ] && { [ ! -e $continent_list ] && file_grabber "https://gist.githubusercontent.com/L1so/e9e17570a4d81f12bb98c8ddc3bab539/raw" $continent_list; }
 
     # Skipping download binary if os was openbsd
-    if is_openbsd; then
+    if [ "$osv" = "bsd" ]; then
 				printf "%s" "Skipping downloading binary"
 				overline
-				return;
     fi
-    
+
     # Download fio if not exist
     if [ "$fio" != "fio" ] && [ ! -f "$fio_path/fio" ]; then
       mkdir -p $fio_path
@@ -441,7 +443,7 @@ user_arch() {
     gb_version=5
     gb_ddl_link="https://cdn.geekbench.com/Geekbench-5.4.4-LinuxARMPreview.tar.gz"
     ;;
-    *) printf "Architecture not found\n"; exit 1;;
+    *) die "Architecture not found"; exit 1;;
   esac
   if [ "$arch" != "x86_64" ]; then unset arg_use_gb45 arg_use_gb4; fi
 }
@@ -460,7 +462,7 @@ sysinfo() {
   checkmark=$(printf '\342\234\224')
   crossmark=$(printf '\342\235\214')
   # Uptime
-  if is_openbsd; then
+  if [ "$osv" = "bsd" ]; then
       s=$(sysctl -n kern.boottime)
       s=${s#*=}
       s=${s%,*}
@@ -499,14 +501,14 @@ sysinfo() {
   if is_installed lscpu && { lscpu 2>&1 | grep -q -- 'Model name' ; }; then
     cpu_model=$(lscpu | awk -F: '/Model name/{ {gsub(/^[ \t]+|[ \t]+$/, "", $2); print $2; exit}}' | sed 's/\(.\{41\}\).*/\1/')
   else
-      if is_openbsd; then
+      if [ "$osv" = "bsd" ]; then
 					cpu_model=$(sysctl -n hw.model)
       else
 					cpu_model=$(awk -F: '/model name/{ {gsub(/^[ \t]+|[ \t]+$/, "", $2); print $2; exit}}' /proc/cpuinfo | sed 's/\(.\{41\}\).*/\1/')
       fi
   fi
+  [ "$osv" = "bsd" ] && cpu_freq=$(printf "@ %s Mhz" $(sysctl -n hw.cpuspeed 2>/dev/null)) || { cpu_freq=$(awk 'NR==1{ print "@ "($1 / 1000) " MHz" }' /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq 2>/dev/null || awk -F: '/cpu MHz/{ {gsub(/^[ \t]+|[ \t]+$/, "", $2); printf("@ %s MHz\n", $2); exit}}' /proc/cpuinfo); }
   cpu_core=$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || getconf _NPROCESSORS_ONLN 2>/dev/null)
-  cpu_freq=$(awk 'NR==1{ print "@ "($1 / 1000) " MHz" }' /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq 2>/dev/null || printf "@ %s Mhz\n" $(sysctl -n hw.cpuspeed 2>/dev/null)) || awk -F: '/cpu MHz/{ {gsub(/^[ \t]+|[ \t]+$/, "", $2); printf("@ %s MHz\n", $2); exit}}' /proc/cpuinfo 
   dmesg | egrep -qe 'AES' && { cpu_aes="$checkmark Enabled" && cpu_aes_j="true"; } || grep -q -m 1 aes /proc/cpuinfo && { cpu_aes="$checkmark Enabled" && cpu_aes_j="true"; } || { cpu_aes="$crossmark Disabled" && cpu_aes_j="false"; }
   dmesg | egrep -qe '(VMX|SVM)' && { cpu_virt="$checkmark Enabled" && cpu_virt_j="true"; } || grep -q -m 1 'vmx\|svm' /proc/cpuinfo && { cpu_virt="$checkmark Enabled" && cpu_virt_j="true"; } || { cpu_virt="$crossmark Disabled" && cpu_virt_j="false"; }
   virt_type="$(print_virtualization)"
@@ -517,14 +519,14 @@ sysinfo() {
   disk_info=$(echo "$df_output" | awk 'NR==2{ print $2 }' | convertsize)
   disk_usage=$(echo "$df_output"| awk 'NR==2{ print $3 }'| convertsize)
   disk_percentage=$(echo "$df_output" | awk 'NR==2{ print $5 }')
-  if is_openbsd; then
+  if [ "$osv" = "bsd" ]; then
       mem_info=$(sysctl -n hw.physmem)
       mem_usage=$(vmstat | tail -n1 | awk '{print ($3+0)}')
       mem_usage=$(echo "$mem_usage * 1024" | bc)
       mem_free=$(echo "$mem_info-$mem_usage" | bc)
       mem_percentage=$(echo "$mem_usage*1024*100/$mem_free" | bc)
       swap_info=$(pstat -s | awk '/dev/ {print $2}' | convertsize)
-      
+
       mem_info=$(echo "$mem_info" | convertsize)
       mem_usage=$(echo "$mem_usage" | bc | convertsize)
       mem_percentage=$(echo "$mem_percentage" "%")
@@ -532,7 +534,7 @@ sysinfo() {
       mem_info=$(awk -F":" '$1~/MemTotal/{print $2}' /proc/meminfo | convertsize)
       mem_usage=$(free -b | awk 'NR==2{printf "%.1f GiB\n", $3/1024^3 }')
       mem_percentage=$(free -b | awk 'NR==2{printf "%.0f%s\n", $3*100/$2, "%" }')
-      swap_info=$(free | awk '/Swap/ {print $2}' | convertsize)  
+      swap_info=$(free | awk '/Swap/ {print $2}' | convertsize)
   fi
 
   printf "%-48s%s\n" "Server Insight" "Hardware Information"
@@ -582,8 +584,7 @@ SYSJSON
   fi
 }
 disk_test() {
-	[ is_openbsd ] && return 1
-  [ "$arg_skip_disk" = "true" ] && return 1
+  { [ "$arg_skip_disk" = "true" ] || [ "$osv" = "bsd" ]; } && return 1
   lsblkfifo="${benchy_path}/lsblk.fifo"; fiofile="${benchy_path}/fio.log"; fiores="${benchy_path}/fio_res.log"
   [ -p "$lsblkfifo" ] || mkfifo -m 600 "$lsblkfifo"
   print_space 1
@@ -835,13 +836,14 @@ EOF
     esac
   fi
 }
-
-shuf() {
-    return $(awk -v min=$(echo $1 | cut -f1 -d'-') \
-		 -v max=$(echo $1 | cut -f2 -d'-') \
-		 'BEGIN{srand(); print int(min+rand()*(max-min+1))}')
+cshuf() {
+  dasnumber="$1"
+  if [ "$osv" = "bsd" ]; then
+    jot -w %i -r 1 "${dasnumber%-*}" "$((${dasnumber#*-}+1))"
+  else
+    shuf -i "$dasnumber" -n 1
+  fi
 }
-
 runiperf() {
   # Define argument
   run_url="$1"
@@ -853,8 +855,7 @@ runiperf() {
   sn=1
   while [ $sn -le 5 ]; do
     printf "%s" "Performing iperf3 send test to $run_host (Attempt #$sn of 5)"
-      shuf $run_port
-      vport=$?
+    vport=$(cshuf $run_port)
     iperf_sendlog=$(timeout 15 $iperf $run_flags -c $run_url -p $vport -P 6 --format k 2>/dev/null | awk '/SUM/ && /sender/{ print $6 }')
     if [ "$?" -eq 0 ]; then sleep 1 && overline && break; else sleep 3 && overline; fi
     sn=$(( sn + 1 ))
@@ -862,9 +863,8 @@ runiperf() {
   # Receive test 5 times
   rn=1
   while [ $rn -le 5 ]; do
-      printf "%s" "Performing iperf3 receive test to $run_host (Attempt #$rn of 5)"
-      shuf $run_port
-      vport=$?
+    printf "%s" "Performing iperf3 receive test to $run_host (Attempt #$rn of 5)"
+    vport=$(cshuf $run_port)
     iperf_reclog=$(timeout 15 $iperf $run_flags -c $run_url -p $vport -P 6 --format k -R 2>/dev/null | awk '/SUM/ && /sender/{ print $6 }')
     if [ "$?" -eq 0 ]; then sleep 1 && overline && break; else sleep 3 && overline; fi
     rn=$(( rn + 1 ))
@@ -1015,12 +1015,12 @@ SPTJSON
 }
 geekbench_test() {
   # Skip geekbench on input argument
-	if is_openbsd; then printf "%s\n" "Geekbench doesnt support *BSD, exiting test.." && return 1; fi
+  [ "$osv" = "bsd" ] && die "Geekbench doesnt support *BSD, exiting test.."
   [ "$arg_skip_gb" = "true" ] && return 1
   # Exit if ipv6 only
-  [ "$ipv4_status" = "false" ] && printf "%s\n" "Geekbench doesn't work over ipv6, exiting test.." && return 1
+  [ "$ipv4_status" = "false" ] && die "Geekbench doesn't work over ipv6, exiting test.."
   # Check if machine was musl library
-  if ldd /bin/ls | grep -q 'musl'; then printf "%s\n" "Geekbench does not support musl library, exiting test.." && return 1; fi
+  if ldd /bin/ls | grep -q 'musl'; then die "Geekbench does not support musl library, exiting test.."; fi
   print_space 1
   if [ "$gb_version" -eq 5 ]; then
     # Geekbench 5
@@ -1143,8 +1143,7 @@ GBJSON
       fi
       rm -f "$gbfile" "$gbfile_4" "$gbfile_5"
     else
-      printf "%s\n" "Geekbench $gb_version run failed, please retry again"
-      return 1
+      die "Geekbench $gb_version run failed, please retry again"
     fi
   } | parse_output
 }
